# Generated by Django 4.2.7 on 2023-12-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='quality',
            new_name='quantity',
        ),
    ]
